---
# tel-it-security-automation :- Ansible roles for automated security hardening.  
# Copyright (c) 2019 Markus Schumburg, [...] Deutsche Telekom AG 
# contact: devsecops@telekom.de 
# This file is distributed under the conditions of the Apache-2.0 license. 
# For details see the files LICENSING, LICENSE, and/or COPYING on the toplevel.

# ========================================================================
# Deutsch Telekom IT - DevSecOps Team
# ------------------------------------------------------------------------
# Security Hardening & Compliance Checks
# Secure Shell (3.04)
#
# Main Tasks
# ========================================================================

# Stop playbook if Linux distro and version is not supported.
- fail:
    msg: "Your {{ansible_distribution}} version {{ ansible_distribution_version }} is not supported!"
  when: (ansible_distribution == "RedHat" and ansible_distribution_major_version != "7") and
        (ansible_distribution == "RedHat" and ansible_distribution_major_version != "8") and
        (ansible_distribution == "CentOS" and ansible_distribution_major_version != "7") and
        (ansible_distribution == "Amazon" and aansible_distribution_major_version != "2") and
        (ansible_distribution == "Suse" and ansible_distribution_major_version != "12") and
        (ansible_distribution == "Suse" and ansible_distribution_major_version != "15") and
        (ansible_distribution == "Ubuntu" and ansible_distribution_version != "16.04") and
        (ansible_distribution == "Ubuntu" and ansible_distribution_version != "18.04")

# Generates a user with root rights and ssh access with public-key.
- name: configure a default user with root rights
  user:
    name: "{{ user_name }}"
    shell: /bin/bash
    password: "{{ password|password_hash('sha512') }}"
    createhome: yes
    groups: "{{ group_ssh }},{{ group_sudo }}"
    append: yes
  when: config_new_user

# Read variables for detected OS from '/vars/var_<linux-os>.yml' files
- name: read variables for redhat 7
  include_vars: "vars_os_redhat_7.yml"
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "7"

- name: read variables for redhat 8
  include_vars: "vars_os_redhat_8.yml"
  when: ansible_distribution == "RedHat" and ansible_distribution_major_version == "8"

- name: read variables for centos 7
  include_vars: "vars_os_centos_7.yml"
  when: ansible_distribution == "CentOS" and ansible_distribution_major_version == "7"

- name: read variables for amazon linux
  include_vars: "vars_os_amazon_2.yml"
  when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "2"

- name: read variables for suse 12
  include_vars: "vars_os_suse_12.yml"
  when: ansible_os_family == "Suse" and ansible_distribution_major_version == "12"

- name: read variables for suse 15
  include_vars: "vars_os_suse_12.yml"
  when: ansible_os_family == "Suse" and ansible_distribution_major_version == "15"

- name: read variables for ubuntu 16.04
  include_vars: "vars_os_ubuntu-16.yml"
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "16.04"

- name: read variables for ubuntu 18.04
  include_vars: "vars_os_ubuntu-18.yml"
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "18.04"

- include_vars: vars_ssh(01)ssh-requirements.yml

- import_tasks: ssh(01)all.yml